# Generated by Django 5.2.17 on 2026-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('page_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('revision_id', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('wikitext_zlib', models.BinaryField()),
            ],
        ),
    ]
