# Generated by Django 5.2.17 on 2026-10-04 22:37

from django.db import migrations
from django.contrib.postgres.operations import (
    TrigramExtension,
    UnaccentExtension,
)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
